[package]
name = "validitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsecp256k1 = "0.7.1"
serde = "1.0.145"
sha3 = "0.10.6"
candid = "0.8.3"
hex = "0.4"